### ISSUE TITLE
"Show Only Latest" functionality does not work

### ISSUE THREAD

**Issue by ProfMatthewHz** [UBAutograding/Autolab#42]
Near the top of the assignment's "Manage Submission" area there is a checkbox labeled "Show Only Latest". I recall this working at one point in time, but it is currently not working in Firefox (v. 62.0.3) nor in Chrome (v. 69.0.3497.100). This is a very low priority item for me, but figured I should report it (and possibly "fix" this by hiding the checkbox).

**Comment by Searay-330** [comment]
ill check it out tonight

**Comment by Searay-330** [comment]
as it turns out that checkbox only applies to searches i will change this
