### ISSUE TITLE
Sort By IP Address

### ISSUE THREAD

**Issue by ProfMatthewHz** [UBAutograding/Autolab#44]
In the "Manage Submission" page, could we add sorting submissions by the IP address column? This would make help when trying to ferret out obvious cases of cheating.

**Comment by Searay-330** [comment]
sort as in just grouping or is there some way of sorting ips that you would like to see?

**Comment by ProfMatthewHz** [comment]
Grouping, I guess. I guess I was hoping whatever library is being used had a standard "click on a column header to have items ordered alphabetically" option so this would be relatively simple. If it would take a lot more work, I would not bother with it.

**Comment by Searay-330** [comment]
well i can do any kind of sorting since we had such wonderful instruction on comparators so i was just curious how they should be sorted since they are not really numbers

**Comment by ProfMatthewHz** [comment]
Alphabetical would be fine. I do not know that there would really be any order beyond grouping similar IP addresses.

**Comment by Searay-330** [comment]
ok ill get on it tonight
