### ISSUE TITLE
Clearing tweak value reverts value instead of zeroing

### ISSUE THREAD

**Issue by ahughes6** [UBAutograding/Autolab#47]
This pertains to the Tweak feature to adjust a submission score (e.g., https://autograder.cse.buffalo.edu/courses/*/assessments/*/submissions/*/edit). Entries that are cleared are reverted after clicking commit.

To reproduce:

1. Enter any tweak value, for instance 5. Click Update Submission.
2. Return to the tweak page.
3. Delete the tweak value. Click Update Submission.

The tweak value 5 will remain.

The only current workaround I found is to set the tweak to 0 the second time around instead of clearing it.

**Comment by Searay-330** [comment]
i do recall talking about this ill have a patch ready to go in a few days
