### ISSUE TITLE
Popover on view gradesheet appears at top left of page

### ISSUE THREAD

**Issue by ahughes6** [UBAutograding/Autolab#53]
When clicking on an email address on the "View Gradesheet" page of an assignment (open an assignment and click Grade Submissions), the popover window that appears always appears at the top left of the page (absolute). If you are scrolled on the page, you will have to scroll back up to the top to view it.

This issue has been reproduced multiple times in Chrome.

**Comment by ahughes6** [comment]
To add: this used to appear at the location of the click/at the email address clicked.

**Comment by Searay-330** [comment]
ok i have never liked this popup anyway i may rework it rather than reposition it either way ill look at fixing it today/tomorrow

**Comment by Searay-330** [comment]
fixed
