### ISSUE TITLE
Incomplete grades being shown

### ISSUE THREAD

**Issue by ProfMatthewHz** [UBAutograding/Autolab#67]
I am getting a lot of reports that students cannot see their full grade for CSE115's Lab1. There were two "problems" in this assignment. I see students' totals in my gradebook, but they are telling me they can only see the result from the first "problem".

This may sound minor, but 600+ students freaking out over lost points == lots of emails.

**Comment by Searay-330** [comment]
can be worked around by releasing all grades in the assignment admin options.
